/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CadastroUser': RouteRecordInfo<'/CadastroUser', '/CadastroUser', Record<never, never>, Record<never, never>>,
    '/Colaboradores/ColaboradoresAdm': RouteRecordInfo<'/Colaboradores/ColaboradoresAdm', '/Colaboradores/ColaboradoresAdm', Record<never, never>, Record<never, never>>,
    '/Colaboradores/ColaboradorUser': RouteRecordInfo<'/Colaboradores/ColaboradorUser', '/Colaboradores/ColaboradorUser', Record<never, never>, Record<never, never>>,
    '/Colaboradores/ViewColaboradores': RouteRecordInfo<'/Colaboradores/ViewColaboradores', '/Colaboradores/ViewColaboradores', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/financeiro/FluxoCaixa': RouteRecordInfo<'/financeiro/FluxoCaixa', '/financeiro/FluxoCaixa', Record<never, never>, Record<never, never>>,
    '/financeiro/ListaHorizontal': RouteRecordInfo<'/financeiro/ListaHorizontal', '/financeiro/ListaHorizontal', Record<never, never>, Record<never, never>>,
    '/financeiro/ListaVertical': RouteRecordInfo<'/financeiro/ListaVertical', '/financeiro/ListaVertical', Record<never, never>, Record<never, never>>,
    '/financeiro/OrcamentoMes': RouteRecordInfo<'/financeiro/OrcamentoMes', '/financeiro/OrcamentoMes', Record<never, never>, Record<never, never>>,
    '/financeiro/ReceitasPeriodo': RouteRecordInfo<'/financeiro/ReceitasPeriodo', '/financeiro/ReceitasPeriodo', Record<never, never>, Record<never, never>>,
    '/financeiro/StatisticsDash': RouteRecordInfo<'/financeiro/StatisticsDash', '/financeiro/StatisticsDash', Record<never, never>, Record<never, never>>,
    '/Importacao': RouteRecordInfo<'/Importacao', '/Importacao', Record<never, never>, Record<never, never>>,
    '/jornada/JornadaColabAdmGrid': RouteRecordInfo<'/jornada/JornadaColabAdmGrid', '/jornada/JornadaColabAdmGrid', Record<never, never>, Record<never, never>>,
    '/jornada/JornadaGrid': RouteRecordInfo<'/jornada/JornadaGrid', '/jornada/JornadaGrid', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Tabela': RouteRecordInfo<'/Tabela', '/Tabela', Record<never, never>, Record<never, never>>,
  }
}
